### ISSUE TITLE
Great book, thank you for it!

### ISSUE THREAD

**Issue by forj1900** [makeyourownneuralnetwork/makeyourownneuralnetwork#11]
However I can't run this example. When I run it, I've got a message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-54d918467417> in <module>()
      6 
      7     # use the filename to set the correct label
----> 8     label = int(image_file_name[-5:-4])
      9 
     10     # load image data from png files into an array

ValueError: invalid literal for int() with base 10: 'e'

```

Everything looks fine after that but at the end the code tells 
```
('network says ', 6)
no match!
```

**Comment by makeyourownneuralnetwork** [comment]
that code int(image_file_name[-5:-4]) tries to extract the correct label from the filename ... so the filename needs to be correct

what file name are you using?

**Comment by forj1900** [comment]
Message are coming due to this file: 2828_my_own_image.png, it is in the folder "my_own_images" on GitHub. But why the code tells "no match!"? I've just check, all other filenames are correct.

**Comment by makeyourownneuralnetwork** [comment]
ok - I agree this is a big. I will fix this and do a blog post to explain how to use this. 

Thanks for raising this.

**Comment by camx** [comment]
Tariq,

The following code will work with your filenames

for image_file_name in glob.glob('my_own_images/2828_my_own_*.png'):
    lfn = image_file_name[:-4].split('_')[5:]
    label = "_".join(lfn)

A simple solution -- you could surround the parts you want to keep as
labels with single quotes in the filename

my_own_images\2828_my_own_'5'.png

my_own_images\2828_my_own_'noisy_6'.png


And simply extract the labels with ...


for image_file_name in glob.glob('my_own_images/2828_my_own_*.png'):
    label = image_file_name.split("'")[1]

**Comment by makeyourownneuralnetwork** [comment]
hi everything - thanks for your feedback and ideas.

I fixed the bug ... it was this change 

- from: `glob.glob('my_own_images/2828_my_own_*.png')`

- to: g`lob.glob('my_own_images/2828_my_own_?.png')`

The pattern is only supposed to match file names like 2828_my_own_3.png or 2828_my_own_7.png .. but not 2828_my_own_image.png, which is a file used for another experiment.

The change is a better pattern as it only allows one character in that wildcard. 

This shouldn't need a blog post fix .. I hope this helps. If not get back to me!

The updated notebook is in the repository now: [https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part3_load_own_images.ipynb](https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part3_load_own_images.ipynb)

Thanks again @camx and @forj1900 :)

**Comment by forj1900** [comment]
<img width="392" alt="screenshot 2017-05-10 22 48 18" src="https://cloud.githubusercontent.com/assets/10003159/25915581/036ea560-35d3-11e7-9db1-b74d7ea755c2.png">

Sorry to bother you, but I still have a problem...
Why the network says "no match!"?

**Comment by makeyourownneuralnetwork** [comment]
hi @forj1900 - there could be 2 things happening here.

1. The network hasn't been trained enough to ensure the accuracy rate is high enough. There will always be some that it gets wrong. But a 97% acuracy (over 10,000 test set) should give you mostly correct matches.

2. The image is very different from the training data. I think this is what is happening. If you look at the training data the digits are a bit larger, and centred. This one isn't .. so the networks hasnt learned to recognise such images. I found this myself when I was drawing my own digits by hand - if they were too small, or off-centre they weren't recognised well.

If you really want to classify this one, I would enlarge the original image and also centre it better.

Does that help?

**Comment by forj1900** [comment]
All images are coming from the GitHub...
Do I understand correctly, that the last part of the code is trying to recognise only one image which is assign by this:  

```
# record to test
item = 1
```

If my assumption is correct, then only value ` 2 `and `4` of the `item` goest to success.

**Comment by makeyourownneuralnetwork** [comment]
took me a while to work out which file you were referring to!

the notebook `part3_neural_network_mnist_and_own_data.ipyn`b does the following:

- trains a neural network against the mist training data
- then loads the images you can created, which have filename `my_own_images/2828_my_own_?.png`
- the code doesn't test all the images, we simply choose one to test, that's what the `item` variable sets. 
- if there are 5 images, then `item = 1` tests the second (0 being the first)

I hope that helps!

Success will depend on training (which is inherently random, remember) so sometimes you'll get all of the images correctly classified, and sometimes not so. The book discusses things you can do to improve training, like increasing epochs, or adding rotated versions of the images to the data set.
